a=int(input("enter value:"))
b=float(input("enter value:"))
c=complex(input("enter value:"))
i=complex(input("enter value:"))
d=bool(input("enter value:"))
j=bool(input("enter value:"))
e=str(input("enter value:"))
f=list(input("enter value:"))
g=tuple(input("enter value:"))
h=set(input("enter value:"))
Addition=(a+b)
Substraction=(a-b)
Multiplication=(a*b)
Division=(a/b)
floor_division=(a//b)
power=(a**b)
complex_number_Addition=(c+i)
complex_number_Substraction=(c-i)
complex_number_Multiplication=(c*i)
complex_number_Division=(c/i)
bool_And=(d and j)
bool_Or=(d or j)
bool_Not=(not d)
bool_Xor=(d ^ j)
bool_Nand=(not(d and j))
bool_Nor=(not(d or j))
bool_Xnor=(not(d ^ j))
str_Concatenation=(e+e)
str_Replication=(e*3)
str_Slicing=(e[0:3])
str_Reverse=(e[::-1])
str_Length=(len(e))
str_Uppercase=(e.upper())
str_Lowercase=(e.lower())
str_Capitalize=(e.capitalize())
str_Title=(e.title())
str_Strip=(e.strip())
str_Replace=(e.replace("a","b"))
str_Split=(e.split())
str_Join=("-".join(e))
str_Find=(e.find("a"))
str_Count=(e.count("a"))
str_Isalnum=(e.isalnum())
str_Isalpha=(e.isalpha())
str_Isdigit=(e.isdigit())
str_Islower=(e.islower())
str_Isupper=(e.isupper())
str_Istitle=(e.istitle())
str_Capitalize=(e.capitalize())
print(a)
print(type(a))
print(b)
print(type(b))
print(c)
print(type(c))
print(d)
print(type(d))
print(e)
print(type(e))
print(f)
print(type(f))
print(g)
print(type(g))
print(h)
print(type(h))
print("Addition of a and b is:",Addition)
print(type(Addition))
print("Substraction of a and b is:",Substraction)
print(type(Substraction))
print("Multiplication of a and b is:",Multiplication)
print(type(Multiplication))
print("Division of a and b is:",Division)
print(type(Division))
print("Floor Division of a and b is:",floor_division)
print(type(floor_division))
print("Power of a and b is:",power)
print(type(power))
print("Addition of c and i is:",complex_number_Addition)
print(type(complex_number_Addition))
print("Substraction of c and i is:",complex_number_Substraction)
print(type(complex_number_Substraction))
print("Multiplication of c and i is:",complex_number_Multiplication)
print(type(complex_number_Multiplication))
print("Division of c and i is:",complex_number_Division)
print(type(complex_number_Division))
print("And of d and j is:",bool_And)
print(type(bool_And))
print("Or of d and j is:",bool_Or)
print(type(bool_Or))
print("Not of d is:",bool_Not)
print(type(bool_Not))
print("Xor of d and j is:",bool_Xor)
print(type(bool_Xor))
print("Nand of d and j is:",bool_Nand)
print(type(bool_Nand))
print("Nor of d and j is:",bool_Nor)
print(type(bool_Nor))
print("Xnor of d and j is:",bool_Xnor)
print(type(bool_Xnor))